repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 【一胜百】一胜百导航,模具钢导航,一胜百模具钢,一胜百官网 · ASSAB
alias_en: Ysb-dh
alias_cn: 一胜百导航
description: 一胜百导航是全网独家首发的模具钢材行业导航，综合了各地区模具钢代理、模具钢资讯、机械制造行情、一胜百官网、一胜百模具钢资讯等多种类型的网站！
keywords: 模具钢,模具钢导航,一胜百导航,模具钢材
url: http://www.ysb-dh.com

author: TSE
author_url: #
organization: TEELAB
organization_url: http://teelab.net
contact: 13322037[at]qq[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor